import { BuilderState } from '@/store/useBuilderStore';

export interface MarkdownResult {
  header: string;
  customLanguages: string;
  widgets: string;
  footer: string;
  full: string;
}

export function generateMarkdown(state: BuilderState): MarkdownResult {
  const empty = { header: '', customLanguages: '', widgets: '', footer: '', full: '' };
  if (!state.username) {
    return { ...empty, full: '<!-- Please enter your GitHub username to generate the README -->' };
  }

  const {
    username,
    showStats,
    showStreak,
    showTrophies,
    showTopRepos,
    includeContributions,
    languageLimit,
    languageLayout,
    languageDisplayType,
    manualSkills,
    hiddenLanguages,
    hiddenSkills,
    badgeColorMode,
    badgeSize,
    showCustomLanguages,
    theme,
    customBgColor,
    customTextColor,
    customIconColor,
    customBorderColor,
    hideBorder,
    layout,
    borderRadius,
    showGlow,
    animationSpeed,
    donutHoleSize,
    startAngle,
    barHeight,
    cardsPerRow
  } = state;

  let themeParams = `&theme=${theme}`;
  if (theme === 'custom') {
    themeParams = `&bg_color=${customBgColor}&title_color=${customTextColor}&text_color=${customTextColor}&icon_color=${customIconColor}&border_color=${customBorderColor}`;
  }
  if (hideBorder) {
    themeParams += '&hide_border=true';
  }

  const baseUrl = typeof window !== 'undefined' ? window.location.origin : 'https://github-customizer.vercel.app';

  const header = `<h1 align="center">Hi there, I'm ${username} 👋</h1>\n\n`;

  let customLanguages = '';
  if (showCustomLanguages) {
    if (languageDisplayType === 'analytics') {
      const advancedParams = `&borderRadius=${borderRadius}&showGlow=${showGlow}&animationSpeed=${animationSpeed}&donutHoleSize=${donutHoleSize}&startAngle=${startAngle}&barHeight=${barHeight}&cardsPerRow=${cardsPerRow}`;
      customLanguages = `<div align="center">\n  <img src="${baseUrl}/api/github-languages?username=${username}&include_contribs=${includeContributions}&limit=${languageLimit}&layout=${languageLayout}${themeParams}${advancedParams}" alt="Detailed Language Analytics" />\n</div>\n\n`;
    } else {
      customLanguages = `<div align="center">\n`;
      manualSkills.filter(s => !hiddenSkills.includes(s)).forEach(skill => {
        const color = badgeColorMode === 'brand' ? '' : `&color=${customIconColor}`;
        customLanguages += `  <img src="${baseUrl}/api/badge?name=${encodeURIComponent(skill)}${color}&size=${badgeSize}" alt="${skill}" />\n`;
      });
      customLanguages += `</div>\n\n`;
    }
  }

  let widgets = '';
  const displayFlex = layout === 'grid' ? '<div align="center">\n' : '';
  const displayFlexEnd = layout === 'grid' ? '</div>\n' : '';

  let widgetsContent = '';

  if (showTrophies) {
    widgetsContent += `  <img src="https://github-profile-trophy.vercel.app/?username=${username}&theme=${theme === 'custom' ? 'flat' : theme}&no-frame=false&no-bg=true&margin-w=15" alt="trophies" />\n`;
  }

  if (showStats) {
    widgetsContent += `  <img src="https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true${themeParams}" alt="${username}'s GitHub Stats" />\n`;
  }

  if (showStreak) {
    widgetsContent += `${layout === 'stacked' ? '  <br/>\n' : '  '}<img src="https://github-readme-streak-stats.herokuapp.com/?user=${username}${themeParams.replace('bg_color', 'background').replace('title_color', 'stroke').replace('text_color', 'currStreakNum').replace('icon_color', 'fire')}" alt="${username}'s GitHub Streak" />\n`;
  }

  if (showTopRepos) {
    widgetsContent += `${layout === 'stacked' ? '  <br/>\n' : '  '}<img src="https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=github-readme-stats${themeParams}" alt="Pinned Repo" />\n`;
  }

  if (widgetsContent) {
    widgets = `${displayFlex}${widgetsContent}${displayFlexEnd}`;
  }

  const footer = `\n<!-- Generated by GitCustomize (github-customizer.vercel.app) -->\n`;

  return {
    header,
    customLanguages,
    widgets,
    footer,
    full: `${header}${customLanguages}${widgets}${footer}`
  };
}
