import { BuilderState } from '@/store/useBuilderStore';

export function generateMarkdown(state: BuilderState): string {
  if (!state.username) {
    return '<!-- Please enter your GitHub username to generate the README -->';
  }

  const {
    username,
    showStats,
    showLanguages,
    showStreak,
    showTrophies,
    showTopRepos,
    includeContributions,
    languageLimit,
    languageLayout,
    languageDisplayType,
    manualSkills,
    hiddenLanguages,
    hiddenSkills,
    badgeColorMode,
    badgeSize,
    showCustomLanguages,
    theme,
    customBgColor,
    customTextColor,
    customIconColor,
    customBorderColor,
    hideBorder,
    layout
  } = state;

  let themeParams = `&theme=${theme}`;
  if (theme === 'custom') {
    themeParams = `&bg_color=${customBgColor}&title_color=${customTextColor}&text_color=${customTextColor}&icon_color=${customIconColor}&border_color=${customBorderColor}`;
  }
  if (hideBorder) {
    themeParams += '&hide_border=true';
  }

  const align = layout === 'stacked' ? 'center' : 'left';
  const displayFlex = layout === 'grid' ? '\n<div align="center">\n' : '';
  const displayFlexEnd = layout === 'grid' ? '\n</div>\n' : '';

  let markdown = `<h1 align="center">Hi there, I'm ${username} 👋</h1>\n\n`;

  if (showTrophies) {
    markdown += `<div align="center">\n  <img src="https://github-profile-trophy.vercel.app/?username=${username}&theme=${theme === 'custom' ? 'flat' : theme}&no-frame=false&no-bg=true&margin-w=15" alt="trophies" />\n</div>\n\n`;
  }

  if (showStats || showLanguages || showStreak || showTopRepos || showCustomLanguages) {
    if (languageDisplayType === 'analytics' || !showCustomLanguages) {
      markdown += displayFlex;

      if (showCustomLanguages && languageDisplayType === 'analytics') {
        const baseUrl = typeof window !== 'undefined' ? window.location.origin : 'https://github-customizer.vercel.app';
        markdown += `  <img src="${baseUrl}/api/github-languages?username=${username}&include_contribs=${includeContributions}&limit=${languageLimit}&layout=${languageLayout}${themeParams}" alt="Detailed Language Analytics" />\n`;
      }
    } else if (languageDisplayType === 'badges' && showCustomLanguages) {
      markdown += `\n<div align="center">\n`;
      
      // We'll use a placeholder for the languages in the markdown generation 
      // because we don't fetch them synchronously here. 
      // Instead, we'll suggest the user adds them manually or we'll generate 
      // the list of manual skills first.
      
      const baseUrl = typeof window !== 'undefined' ? window.location.origin : 'https://github-customizer.vercel.app';
      
      manualSkills.filter(s => !hiddenSkills.includes(s)).forEach(skill => {
        const color = badgeColorMode === 'brand' ? '' : `&color=${customIconColor}`;
        markdown += `  <img src="${baseUrl}/api/badge?name=${encodeURIComponent(skill)}${color}&size=${badgeSize}" alt="${skill}" />\n`;
      });
      
      markdown += `</div>\n\n`;
    }

    if (showStats) {
      markdown += `  <img src="https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true${themeParams}" alt="${username}'s GitHub Stats" />\n`;
    }

    if (showStreak) {
      markdown += `${layout === 'stacked' ? '<br/><br/>\n' : '  '}<img src="https://github-readme-streak-stats.herokuapp.com/?user=${username}${themeParams.replace('bg_color', 'background').replace('title_color', 'stroke').replace('text_color', 'currStreakNum').replace('icon_color', 'fire')}" alt="${username}'s GitHub Streak" />\n`;
    }
    
    if (showLanguages) {
      markdown += `${layout === 'stacked' ? '<br/><br/>\n' : '  '}<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=${username}&layout=compact${themeParams}" alt="Top Languages" />\n`;
    }

    if (showTopRepos) {
      markdown += `${layout === 'stacked' ? '<br/><br/>\n' : '  '}<img src="https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=github-readme-stats${themeParams}" alt="Pinned Repo" />\n`;
    }

    markdown += displayFlexEnd;
  }

  markdown += `\n<!-- Generated by GitCustomize (github-customizer.vercel.app) -->\n`;

  return markdown;
}
